services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: genai-backend
    ports:
      - "8000:8000"
    environment:
      - PDF_PATH=/mnt/data/sample_knowledge.txt

    volumes:
      - ./data:/mnt/data:ro
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: genai-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped
